### PR TITLE
the after-open setTimeout is now more resilient to synchronous testing

### PR DESCRIPTION
**Pull request by SohumB**
We were running into issues in automated testing of drop, where we synchronously run a lot of events that open and close drop instances. This makes the case we kept hitting go away, and is probably(?) what drop should be doing anyway.

### CODE REVIEW

**Comment by geekjuice** [comment]
Sorry for the delay. Not entirely sure how this makes `setTimeout` more resilient. It may be something I'm missing, but if you don't mind explaining a little more, that'd be great :smiley_cat: _cat:

**Comment by SohumB** [comment]
Hey! So basically we had a unit test that opened and closed a bunch of drop instances, synchronously. Each time one was opened, it would register on the next tick that handler.

But then said drop instance would be synchronously destroyed, so when the next tick came around, `this.drop` would be undefined and cause drop to throw an error.

That's all!

**Comment by geekjuice** [comment]
Ah, I think that's valid a point. Would you like to open a new PR and add that change (since the repository has changed quite a bit since this was opened). Or if you don't care about contribution commits :sweat_smile: I can just add that change for you.

**Comment by SohumB** [comment]
Done https://github.com/HubSpot/drop/pull/77 , thanks!

**Pull request closed without merging**
