### PR TITLE
Proper UMD wrapper for Drop lib

### PR DESCRIPTION
**Pull request by lltwox**
I've added umd wrapper, so lib can be used with requirejs.

### CODE REVIEW

**Comment by ngault** [comment]
You mention RequireJS, but this UMD also looks to have CommonJS support... Which would be awesome.  Have you tested NPM?

**Comment by lltwox** [comment]
It doesn't work with npm (and broweserify), because it lacks proper info in package.json. It should have "main" field with main file and dependency on tether. Tether itself misses exported module, so simply adding dependency doesn't make it work. There is some hacks to fix all that, but I think it's better to start with Tether and then all dependent modules.

In addition, at the moment Drop installs Tether with bower to use it in a bundled file. If npm dependency on Tether will be added, it makes sense to drop bower and use installed one from node_modules. Btw, same thing happening with Select and Tooltip libs.

So, at the moment amd works, global file works, commonjs works, but most likely fail because of  dependencies.

**Comment by ngault** [comment]
`@lltwox` thanks so much for the info.  I'm not sure I follow you when you say that "Tether itself misses exported module, so simply adding dependency doesn't make it work."  I see that Tether is hosted on npm now.  Are you saying that the ONLY requirement for a pure CommonJS/npm implementation (without Bower) of Drop could be achieved with modifications to `package.json`   ?

BTW, I see that you, like me, are trying to use dependency management for the whole suite of Tether dependent components: Tooltip, Drop, Select, Shepherd etc.  There is so much confusion across in the Issues forums for each of these repos.  So many folks (like my team) continue to use their own hacks.   You seem to be in a great position to do the community a huge service, which is to document exactly the npm/Browserify issues.  It would be great if we could a UNIFIED story (even better, working code!) across all of Tether, Drop, Tooltip, Select, and Shepherd.  Many devs would like to know:

 - current npm/Browserify & AMD support for each of the 5 projects 
 - how to specify dependencies for using Drop and Tooltip together, given that Drop is a subset of Tooltip
 - known issues and guidance with the ordering of dependencies of the 4 projects depending on Tether

It looks like Hubspot, the company, has abandoned these projects, and the original authors are now focused on support for these projects within Eager, which uses an unrelated deployment model.  I think that's a huge mistake, because many committed devs have been leaving these projects over the last year because of obvious neglect for dependency management.  

It would be great if an independent dev could take the lead here.  The effort should probably be centralized in the Tether repo.  I suspect that a number of other devs (like me) would love to help.  Otherwise, I worry that Drop, Tooltip and Select will die in 2015... which would be real shame.

**Comment by lltwox** [comment]
@ngault by "Tether itself misses exported module" I meant, that if you install tether with `npm install --save tether` and then do `require('tether');` in your code – it will fail. This happens because of missing 'main' entry in package.json, which tells node which file to require first from module. This entry was added with last commit to tether's master branch, but not yet published to npm.

I'd love to help. Not sure where to start though, if projects are abandoned.

**Comment by geekjuice** [comment]
@ngault @lltwox  Just to chime in (and take my word with a grain of salt), but HubSpot hasn't actually abandoned these projects. However, you are correct that they have not been getting the love they deserve recently and we are working towards fixing that. 

With that in mind, we do need to re-unify how these projects are distributed on package managers as most of the published packages are outdated and need some fixes applied to them.

**Comment by ngault** [comment]
@lltwox , thanks, now I understand the issue with Tether -- I hadn't realized that the master branch hadn't made it yet to npm.

@geekjuice , it's encouraging to hear that Hubspot sees the need to update these projects.  To be clear, when I say "abandoned", I'm not talking about Vex, Offline, and Shepherd, which are very capably maintained by Eager.  I'm referring strictly to Drop, Tooltip, and Select.  I think it's fair to say that a JS project that doesn't support npm by 2015 isn't going far. 

FWIW, I think 90% of the job is adding proper UMD support across all these libraries, (as @lltwox has done here for Drop).  A bunch of folks could do the entire job in a few hours, but nobody's comfortable owning dependency management going forward for 5 repositories for which they aren't the recognized project leader.  This is a leadership, not a technical, challenge.

**Comment by geekjuice** [comment]
@ngault I completely agree. I'm going to push for getting these issues (at least the published package issues) resolved soon for these `Tether`-based projects. I can't guarantee that it will be done in the next few days (maybe it will), but I can at least tell you that we are aware of them and will be resolved in the near future.

And belated sorry @lltwox that we comment-jacked this PR. I'm going to hold off merging this PR for the time being until we can figure out how to best handle all of these `Tether`-based projects so we don't have this issue again in the future. But I think the direction this PR took is correct in that we should just wrap each project individually and offer bundled options as well.

**Comment by ngault** [comment]
Wow!  Go @geekjuice !

And, thanks, @lltwox for jumpstarting this.  I also apologize for jacking your PR.

**Comment by lltwox** [comment]
@geekjuice @ngault no problem about PR, if it leads to better code.

@geekjuice wrapping will definitely help, but there is more things to do, like ensuring nothing gets exported to global space. I can make a PR for Tether, with changes I'm talking about if it helps and speeds up updates for all libs.

**Comment by geekjuice** [comment]
Sorry for the delay. I've finally gotten around to some long standing updates in https://github.com/HubSpot/drop/pull/68 which includes a proper UMD wrapper. It still needs some adjustments before releasing (for example, it currently exports `Drop` to the global space due to difference in the gulp and broccoli UMD libraries) so having more eyes on that PR would definitely speeds things up and ensure I don't overlook anything.

If you don't mind, I'm going to close this PR in favor of that one, but please feel free to checkout that branch and provide feedback.

**Pull request closed without merging**
